name: Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the workflow on'
        required: true
        type: choice
        options:
          - main
          - dev

jobs:
  Set-Date:
    runs-on: ubuntu-latest
    steps:
      - name: Set date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        
  Dev-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/toomas633/qB-autodelete:${{ env.DATE }}
            ghcr.io/toomas633/qB-autodelete:latest
            docker.io/toomas633/qb-autodelete:latest
            docker.io/toomas633/qb-autodelete:${{ env.DATE }}
          labels: |
            org.opencontainers.image.created=${{ env.DATE }}
